# Generated by Django 4.2.7 on 2024-01-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_image',
        ),
    ]
